name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.9.0
    secrets: inherit
    with:
      run-build: true
      publish: true
      publish-command: 'npm publish'
