name: publish_canary

on:
  workflow_dispatch:

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@push
    secrets: inherit
    with:
      run-lint: true
      run-build: true
      publish: true
      publish-command: 'npm publish'
