name: publish_canary

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@push
    secrets: inherit
    with:
      run-build: true
      publish: true
      publish-command: 'npm publish --tag canary'
